### ISSUE TITLE
access to ctDNA data

### ISSUE THREAD

**Issue by cyye47** [guardant/Zill_2018#1]
Hi!

I just read your publication in Clinical Cancer Research and I'm interested in the cfDNA dataset, which led me to your page. I wonder if there's any cfDNA data and code that I may access. Thank you!

**Comment by carlotarp** [comment]
Hi,

Same here, in the manuscript you say the analysis codes and data are available in this repository however it is empty, could you give me access somehow?

thanks!

carlota.

**Comment by fortuno** [comment]
Hi,

Did any of you ever get access to the data/code supposedly available? In that case I would love to have access too if possible.

Thanks!

Francisco

**Comment by carlotarp** [comment]
No

https://pubpeer.com/publications/CEAC9BEAC3EC2FD610AE03FE0B872C

**Comment by cyye47** [comment]
No

**Comment by gh-dchudova** [comment]
folks, let me get back to the team to check on this.

**Comment by ABCOH** [comment]
I have also made multiple requests for data without success.  In addition to the paper stating the data was available, the journal's policy states, "Publication in an AACR journal is contingent upon the authors’ certification that all materials, data, and protocols described in the manuscript will be made available upon request, if the request is made within six years of publication".  

I believe the journal editors should be contacted so that they can address the issue (ccr@aacr.org, sgh@bcm.edu).  If the team has decided not to post their data, the journal should withdraw the paper as it is not reproducible and does not abide by the terms of the publication.

**Comment by faircloughS** [comment]
Data and code to generate the figures from the paper are available.
